#!/usr/bin/env perl

use Mojo::Base -strict;

use File::Basename 'dirname';
use File::Spec;

push @INC, join('/', File::Spec->splitdir(dirname(__FILE__)), '..', 'lib');

# Check if Mojolicious is installed;
die <<EOF unless eval 'use Mojolicious::Commands; 1';
It looks like you don't have the Mojolicious framework installed.
Please visit http://mojolicio.us for detailed installation instructions.

EOF

# Application
$ENV{CAMINHO_BANCO} ||= '/home/sites/compras/db/banco.sqlite3';
$ENV{MOJO_APP} ||= 'Compras';
$ENV{MOJO_MODE} ||= 'production';

# Start commands
Mojolicious::Commands->start;
